site_name: TorrentFile Docs
site_url: https://alexpdev.github.io/torrentfile
repo_url: https://github.com/alexpdev/torrentfile
site_description: "TorrentFile CLI Documentation and Examples"
copyright: alexpdev 2022

theme:
  name: superhero
  logo: images/torrentfile.png
  favicon: images/favicon.ico

nav:
  - HOME : index.md
  - HELP : Commands.md
  - Examples : Examples.md
  - LICENSE : LGPLv3.md
  - HASHER : Hasher.md
  - TORRENT : Torrent.md
  - INTERACTIVE : Interactive.md
  - EDIT : Edit.md
  - CLI : CLI.md
  - UTILS : Utils.md
  - RECHECK : Recheck.md
  - CHANGELOG : changelog.md


plugins:
  - search
  - autorefs
  - mkapi
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: yes

docs_dir: site/
site_dir: docs/
