site_name: TorrentFile
site_url: https://alexpdev.github.io/torrentfile
repo_url: https://github.com/alexpdev/torrentfile
site_description: "Bittorrent Meta File Creator."
copyright: alexpdev 2021

theme:
  name: material
  logo: torrentfile.png
  favicon: favicon.png

nav:
  - Overview: examples.md
  - CLI: CLI.md
  - Home: index.md
  - Hasher: hasher.md
  - License: LICENSE.md
  - Progress: progress.md
  - Torrent: torrent.md
  - Tests: tests.md
  - Utils: utils.md


plugins:
  - search
  - mkdocstrings

docs_dir: site/
site_dir: docs/
