site_name: TorrentFile
site_url: https://alexpdev.github.io/torrentfile
repo_url: https://github.com/alexpdev/torrentfile
site_description: "Bittorrent Meta File Creator."
copyright: alexpdev 2021

theme:
  name: 'rtd-dropdown'

nav:
  - Home: index.md
  - About: about.md
  - License: LICENSE.md
  - API: API.md
  - Tests: tests.md
  - CLI: CLI.md
  - Hybrid: Hybrid.md
  - TorrentFile: TorrentFile.md
  - TorrentFileV2: TorrentFileV2.md
  - Utils: utils.md


plugins:
  - search
  - mkdocstrings

docs_dir: site/
site_dir: docs/
