site_name: TorrentFile
site_url: https://alexpdev.github.io/torrentfile
repo_url: https://github.com/alexpdev/torrentfile
site_description: "Bittorrent Meta File Creator."
copyright: alexpdev 2021

theme:
  name: material
  logo: torrentfile.png
  favicon: favicon.png

nav:
  - examples: examples.md
  - CLI: CLI.md
  - home: index.md
  - hasher: hasher.md
  - LICENSE: LICENSE.md
  - progress: progress.md
  - torrent: torrent.md
  - tests: tests.md
  - utils: utils.md


plugins:
  - search
  - mkdocstrings

docs_dir: site/
site_dir: docs/
